# Use the official Nginx base image
FROM nginx:latest

# Copy custom configuration file to the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy static files to the container
# COPY static /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]